disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Srachet Rai"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo-small.png"
  secondaryLogo = "logo-small.png"
  # Uncomment and update for a site description:
  # description = "My awesome website"
  # Uncomment to set a custom copyright:
  # copyright = "Copy, _right?_ :thinking_face:"

  [params.author]
    name = "Srachet Rai"
    email = "srachetrai@gmail.com"
    image = "profile.png"      # Place this image in your assets or static folder
    imageQuality = 96
    headline = "Cybersecurity Enthusiast & BTech CSE"
    bio = "I am a cybersecurity professional with a passion for technology, research, and creative design. Welcome to my portfolio!"
    links = [
      { github = "https://github.com/Cryio" },
      { linkedin = "https://linkedin.com/in/srachetrai" },
      { email = "mailto:srachetrai@gmail.com" },
    ]
