# -- Main Menu Configuration --
[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Projects"
  pageRef = "projects"  # Links to content under /projects/ (ensure you have a section with this identifier)
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "posts"     # Adjust based on your content organization for blog posts
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"     # Links to your About page (content/about.md)
  weight = 30

# Create a parent menu for additional resources.
[[main]]
  name = "Resources"
  weight = 40

[[main]]
  name = "Tutorials"
  parent = "Resources"  # This creates a submenu under "Resources"
  pageRef = "tutorials"
  weight = 10

[[main]]
  name = "Docs"
  parent = "Resources"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "Contact"
  url = "/contact/"     # Alternatively, if you have a dedicated contact page
  weight = 50


# -- Footer Menu Configuration --
[[footer]]
  name = "Categories"
  pageRef = "categories"  # Ensure you have a categories section or taxonomy configured
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"        # Similarly, ensure your tags taxonomy is set up
  weight = 20

[[footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 30

[[footer]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 40
