# -- Site Configuration --
baseURL = ""
title = "Srachet Rai - Portfolio"
defaultContentLanguage = "en"
theme = "blowfish"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# -- Theme Options --
# These options control how the theme functions and allow you to customise the display of your website.
# See: https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "fire"
defaultAppearance = "dark"       # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = false
replyByEmail = false

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

# defaultBackgroundImage = "IMAGE.jpg"   # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg"       # used as default for featured images in all articles

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

# -- Header & Footer --
[header]
  # (Merged header: originally "basic" then later "fixed" – using "fixed")
  layout = "fixed"

[header.nav]
  right = [
    { identifier = "projects", name = "Projects", url = "/projects", weight = 1 },
    { identifier = "blog", name = "Blog", url = "/blog", weight = 2 },
    { identifier = "about", name = "About", url = "/about", weight = 3 }
  ]

[footer]
  showMenu = false
  showCopyright = true
  showAppearanceSwitcher = true
  showScrollToTop = true
  showThemeAttribution = false


# -- Custom Parameters --
[params]
  # Shared across all pages
  defaultFeaturedImage = "preview.png"
  defaultBackgroundImage = "preview.png"
  borderRadius = "lg"
  boxShadow = "xl"
  description = "Portfolio of Srachet Rai – Cybersecurity Enthusiast & BTech CSE"
  favicon = "favicon.ico"
  colorScheme = "fire"
  primaryColor = "purple"  # options: slate, gray, zinc, neutral, stone, red, orange, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose
  container = "full"  # critical for full-width layout (options: full, constrained)
  
  # Social proof section
  [[params.metrics]]
    icon = "fas fa-shield-alt"
    value = "50+"
    label = "Projects Secured"
  
  [[params.metrics]]
    icon = "fas fa-certificate"
    value = "10+"
    label = "Certifications"

# -- Homepage Settings --
[homepage]
  layout = "background"               # Options: profile, page, hero, background, card, custom
  homepageImage = "preview.png"     # Place your image in the assets folder (or static, as appropriate)
  showRecent = true  
  mainSections = ["/projects/"]             # Show recent articles below the main content
  showMoreLink = true             # Display a “Show More” link at the end of recent articles
  showMoreLinkDest = "/about/"    # Destination for the “Show More” link
  cardView = true                 # Display recent articles as a gallery of cards
  cardViewScreenWidth = true     # Adjust card gallery to full width if needed
  layoutBackgroundBlur = true     # Apply a background blur (used with certain layouts)
  layoutBackgroundHeaderSpace = true
  
# -- Article Settings --
[article]
  # Note: There were two article sections. These have been merged.
  showHero = true              # (If false, hero image won’t show on individual articles)
  heroStyle = "background"      # Valid options: basic, big, background, thumbAndBackground
  showSummary = true
  showRelatedContent = true
  relatedContentLimit = 6
  showDate = true
  showViews = true
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  # showAuthorBottom = false    # (optional)
  layoutBackgroundBlur = true   # Only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false  # Only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"  # (optional)
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = true
  showZenMode = false

# -- Sitemap Settings --
[sitemap]
  excludedKinds = ["taxonomy", "term"]

# -- Taxonomy Settings --
[taxonomy]
  showTermCount = true
  showHero = false
  # heroStyle not set
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

# -- Term Settings --
[term]
  showHero = false
  # heroStyle not set
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# -- Firebase Settings --
[firebase]
  # Uncomment and set your Firebase keys if you use Firebase integrations.
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

# -- Fathom Analytics --
[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

# -- Umami Analytics --
[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = true

# -- Seline Analytics --
[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

# -- BuyMeACoffee Settings --
[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

# -- Verification Settings --
[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  # fediverse = ""

# -- RSSNext Settings --
[rssnext]
  # feedId = ""
  # userId = ""
