baseURL = "https://cryio.github.io/"
title = "Cryio - Portfolio"
theme = "blowfish"

[params]
  description = "Portfolio of Cryio - Cybersecurity Enthusiast"
  favicon = "favicon.ico"
  colorScheme = "auto"

  [params.author]
    name = "Cryio"

[params.nav]
  enabled = true
  menu = "auto"
